name: Hoytus
favicon: null
layout_spectrum: 0.53176
typography_spectrum: 0.24124
title: Hoytus Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b3a88'
    - '#f6b26b'
    - '#e2534b'
    - '#de8fa5'
    - '#8f213e'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.6699081335682422
  rhythmicContrast: 0.4690313080791384
purpose: []
